In [4]:
import pandas as pd 
import numpy as np 
import sklearn

In [5]:
data=pd.read_csv('./Fifa 23 Players Data.csv')

In [6]:
data.head()

Known As           Full Name  Overall  Potential  Value(in Euro)  \
0        L. Messi        Lionel Messi       91         91        54000000   
1      K. Benzema       Karim Benzema       91         91        64000000   
2  R. Lewandowski  Robert Lewandowski       91         91        84000000   
3    K. De Bruyne     Kevin De Bruyne       91         91       107500000   
4       K. Mbappé       Kylian Mbappé       91         95       190500000   

  Positions Played Best Position Nationality  \
0               RW           CAM   Argentina   
1            CF,ST            CF      France   
2               ST            ST      Poland   
3           CM,CAM            CM     Belgium   
4            ST,LW            ST      France   

                                         Image Link  Age  ...  LM Rating  \
0  https://cdn.sofifa.net/players/158/023/23_60.png   35  ...         91   
1  https://cdn.sofifa.net/players/165/153/23_60.png   34  ...         89   
2  https://cdn.sofifa.net/players/188/545/23_60.png   33  ...         86   
3  https://cdn.sofifa.net/players/192/985/23_60.png   31  ...         91   
4  https://cdn.sofifa.net/players/231/747/23_60.png   23  ...         92   

   CM Rating  RM Rating  LWB Rating CDM Rating  RWB Rating  LB Rating  \
0         88         91          67         66          67         62   
1         84         89          67         67          67         63   
2         83         86          67         69          67         64   
3         91         91          82         82          82         78   
4         84         92          70         66          70         66   

  CB Rating RB Rating GK Rating  
0        53        62        22  
1        58        63        21  
2        63        64        22  
3        72        78        24  
4        57        66        21  

[5 rows x 89 columns]

In [9]:
data1=data[data['Overall']>=85]

In [24]:
data1

Known As                     Full Name  Overall  Potential  \
0         L. Messi                  Lionel Messi       91         91   
1       K. Benzema                 Karim Benzema       91         91   
2   R. Lewandowski            Robert Lewandowski       91         91   
3     K. De Bruyne               Kevin De Bruyne       91         91   
4        K. Mbappé                 Kylian Mbappé       91         95   
..             ...                           ...      ...        ...   
86    T. Hernández                Theo Hernández       85         90   
87      Diogo Jota  Diogo José Teixeira da Silva       85         89   
88      P. Gulácsi                 Péter Gulácsi       85         85   
89       Y. Sommer                   Yann Sommer       85         85   
90         M. Reus                    Marco Reus       85         85   

    Value(in Euro) Positions Played Best Position  Nationality  \
0         54000000               RW           CAM    Argentina   
1         64000000            CF,ST            CF       France   
2         84000000               ST            ST       Poland   
3        107500000           CM,CAM            CM      Belgium   
4        190500000            ST,LW            ST       France   
..             ...              ...           ...          ...   
86        76000000               LB           LWB       France   
87        76000000            CF,LW            ST     Portugal   
88        26500000               GK            GK      Hungary   
89        17500000               GK            GK  Switzerland   
90        33500000        CAM,CF,RM           CAM      Germany   

                                          Image Link  Age  ...  LM Rating  \
0   https://cdn.sofifa.net/players/158/023/23_60.png   35  ...         91   
1   https://cdn.sofifa.net/players/165/153/23_60.png   34  ...         89   
2   https://cdn.sofifa.net/players/188/545/23_60.png   33  ...         86   
3   https://cdn.sofifa.net/players/192/985/23_60.png   31  ...         91   
4   https://cdn.sofifa.net/players/231/747/23_60.png   23  ...         92   
..                                               ...  ...  ...        ...   
86  https://cdn.sofifa.net/players/232/656/23_60.png   24  ...         84   
87  https://cdn.sofifa.net/players/224/458/23_60.png   25  ...         84   
88  https://cdn.sofifa.net/players/185/122/23_60.png   32  ...         34   
89  https://cdn.sofifa.net/players/177/683/23_60.png   33  ...         37   
90  https://cdn.sofifa.net/players/188/350/23_60.png   33  ...         85   

    CM Rating  RM Rating  LWB Rating CDM Rating  RWB Rating  LB Rating  \
0          88         91          67         66          67         62   
1          84         89          67         67          67         63   
2          83         86          67         69          67         64   
3          91         91          82         82          82         78   
4          84         92          70         66          70         66   
..        ...        ...         ...        ...         ...        ...   
86         81         84          86         82          86         85   
87         80         84          72         71          72         70   
88         36         34          34         36          34         34   
89         40         37          33         36          33         32   
90         83         85          74         72          74         70   

   CB Rating RB Rating GK Rating  
0         53        62        22  
1         58        63        21  
2         63        64        22  
3         72        78        24  
4         57        66        21  
..       ...       ...       ...  
86        82        85        20  
87        68        70        21  
88        36        34        85  
89        32        32        85  
90        62        70        23  

[91 rows x 89 columns]

In [34]:
numeric_data=data1._get_numeric_data()
numeric_data=numeric_data.to_numpy(dtype=float)
from sklearn.preprocessing import Normalizer

noraml_data=Normalizer().fit_transform(numeric_data)

In [35]:
noraml_data

array([[8.01333080e-07, 8.01333080e-07, 4.75516333e-01, ...,
        4.66710475e-07, 5.45963197e-07, 1.93728876e-07],
       [6.23380644e-07, 6.23380644e-07, 4.38421552e-01, ...,
        3.97319531e-07, 4.31571215e-07, 1.43857072e-07],
       [4.74957793e-07, 4.74957793e-07, 4.38422579e-01, ...,
        3.28816934e-07, 3.34036250e-07, 1.14824961e-07],
       ...,
       [1.62494965e-06, 1.62494965e-06, 5.06601950e-01, ...,
        6.88213970e-07, 6.49979861e-07, 1.62494965e-06],
       [2.45959576e-06, 2.45959576e-06, 5.06387362e-01, ...,
        9.25965463e-07, 9.25965463e-07, 2.45959576e-06],
       [1.28562941e-06, 1.28562941e-06, 5.06689240e-01, ...,
        9.37753220e-07, 1.05875364e-06, 3.47876195e-07]])

In [39]:
from sklearn.decomposition import PCA
reduced_data=PCA(n_components=2).fit_transform(noraml_data)


In [40]:
reduced_data

array([[-0.00615402, -0.00381492],
       [-0.0423909 ,  0.0168338 ],
       [-0.04239328,  0.01682624],
       [-0.0062006 , -0.00379115],
       [-0.0205327 ,  0.0041246 ],
       [-0.00619825, -0.00379612],
       [-0.05445033,  0.02413601],
       [ 0.03731282, -0.02601614],
       [-0.01585777,  0.00152314],
       [-0.00615522, -0.00381941],
       [-0.01595072,  0.00156193],
       [-0.00620545, -0.00379348],
       [-0.01586082,  0.00151228],
       [-0.01586046,  0.00151368],
       [-0.05438838,  0.02409232],
       [ 0.03769587, -0.0262178 ],
       [-0.02054391,  0.00413522],
       [ 0.02023602, -0.01762718],
       [-0.02060248,  0.0041683 ],
       [-0.00615457, -0.00381693],
       [-0.02047953,  0.00409801],
       [-0.04239644,  0.01681477],
       [-0.02047787,  0.00409319],
       [-0.0062059 , -0.00379067],
       [-0.00609435, -0.00384968],
       [-0.02054436,  0.00413346],
       [-0.00614776, -0.00379458],
       [-0.05444884,  0.02413613],
       [-0.042394  ,

In [41]:
from sklearn.cluster import KMeans
.fit(reduced_data)

In [49]:
mbapeh=data.loc[data['Full Name']=='Kylian Mbappé']
messi=data.loc[data['Full Name']=='Lionel Messi']
ronaldo=data.loc[data['Full Name']=='C. Ronaldo dos Santos Aveiro']


In [50]:
from sklearn.pipeline import Pipeline
normalizer=Normalizer()
pca=PCA(n_components=2)
kmeans = KMeans(n_clusters=5, random_state=0, n_init="auto")
pipe = Pipeline(steps=[("scaler", normalizer), ("pca", pca), ("kemans", kmeans)])
pipe.fit(numeric_data)

Pipeline(steps=[('scaler', Normalizer()), ('pca', PCA(n_components=2)),
                ('kemans',
                 KMeans(n_clusters=5, n_init='auto', random_state=0))])

In [55]:
class Model():
    def fit(self,data):
        numeric_data=data._get_numeric_data()
        normalizer=Normalizer()
        pca=PCA(n_components=2)
        kmeans = KMeans(n_clusters=5, random_state=0, n_init="auto")
        self.pipe = Pipeline(steps=[("scaler", normalizer), ("pca", pca), ("kemans", kmeans)])
        self.pipe.fit(numeric_data)

    def transform(self,data):
        numeric_data=data._get_numeric_data()
        return self.pipe.transform(numeric_data)
        

In [56]:
m=Model()
m.fit(data1)
m.transform(messi)
print(pipe.transform(messi_numeric))
print(pipe.transform(ronaldo_numeric))
print(pipe.transform(mbapeh_numeric))

array([[0.03700178, 1.02418807, 0.01431756, 0.04993908, 0.00403117]])